In [2]:
import numpy as np

In [4]:
m1 = np.array([[3, 4], [7, 2], [5, 9]])
m2 = np.array([[3, 1, 5], [6, 9, 7]])

In [12]:
m3 = m1.dot(m2)
m3

array([[33, 39, 43],
       [33, 25, 49],
       [69, 86, 88]])

In [13]:
np.dot(m1, m2)

array([[33, 39, 43],
       [33, 25, 49],
       [69, 86, 88]])

In [14]:
b1 = np.array([[1], [2], [3]])
m3 + b1
b1.shape

(3, 1)

In [16]:
b1

array([[1],
       [2],
       [3]])

In [17]:
m1

array([[3, 4],
       [7, 2],
       [5, 9]])

In [19]:
data = [m1, b1]
np.savez("test.npz", *data)

In [1]:
data = np.load("test.npz")
for key in data.files:
    print(data[key])

NameError: name 'np' is not defined

In [1]:
np.mean((np.random.rand(1000, 1000)-0.5)*0.0001)

NameError: name 'np' is not defined

In [3]:
l = [1]*3
print(sum(l))

3
